class OrderQuery {
  static const String orderMaster = """
    query OrderMaster( \$orderMasterId: Int!){
      orderMaster(orderMasterId: \$orderMasterId){
        id
        orderNumber
        priceDelivery
        priceToPay
        priceTotalProducts
        orderName
        receiver
        address
        detailAddress
        zipCode
        phone
        details{
          product{
            color
            size
            productMaster{
              name
              thumbnail
              brand{
                name
              }
              category{
                name
              }
              subCategory{
                name
              }
            }
            name 
          }
          quantity
          priceTotal
          priceProducts
          priceWork
          priceWorkLabor
          priceOption
        }
      }
    }
  """;

  static const String myOrder = """
    query MyOrder(\$id: ID!){
      defaultBankAccount{
        bankName
        accountNo
        ownerName
      }
      myOrder(id: \$id){
        dateCreated
        id
        coupon{
          couponName
          price
        }
        priceToPay
        orderNumber
        paymentSuccess{
          amount
          requestedAt
          method
        }
        paymentRequest{
          method
          requestedAt
          amount
        }
        priceDelivery
        receiver
        address
        detailAddress
        smarterMoneyHistory{
          amount
        }
        zipCode
        phone
        deliveryRequest
        details {
          id
          userRequest
          studentNames
          draft{
            image
            priceWork
            font
            threadColor
          }
          state
          product{
            color
            size
            productMaster{
              id
              name
              productMasterId
              thumbnail
              brand{
                name
              }
              category{
                name
              }
              subCategory{
                name
              }
            }
            name 
          }
          quantity
          priceTotal
          priceProducts
          priceWork
          priceWorkLabor
          priceOption
          }
      }
    }
  """;

  static const String myOrderByOrderNumber = """
    query myOrderByOrderNumber(\$id: String){
      defaultBankAccount{
        bankName
        accountNo
        ownerName
      }
      myOrderByOrderNumber(orderNumber: \$id){
        dateCreated
        id
        priceToPay
        coupon{
          couponName
          price
        }
        orderNumber
        paymentSuccess{
          amount
          requestedAt
          method
        }
        paymentRequest{
          method
          requestedAt
          amount
        }
        priceDelivery
        receiver
        address
        detailAddress
        smarterMoneyHistory{
          amount
        }
        zipCode
        phone
        deliveryRequest
        details {
          id
          userRequest
          studentNames
          draft{
            image
            priceWork
            font
            threadColor
          }
          state
          product{
            color
            size
            productMaster{
            productMasterId
            id
              name
              thumbnail
              brand{
                name
              }
              category{
                name
              }
              subCategory{
                name
              }
            }
            name 
          }
          quantity
          priceTotal
          priceProducts
          priceWork
          priceWorkLabor
          priceOption
          }
      }
    }
  """;

  static const String myOrders = """
    query MyOrders(\$after: String){
      myOrders(first:10, after: \$after){
        totalCount
        pageInfo{
          endCursor
        }
        edges{
          node{
            orderMasterId
            dateCreated
            orderState
            id
            coupon{
              couponName
              price
            }
            details{
            id
              state
              delivery{
                deliveryAgency{
                  name
                }
                trackingNumber
                photo
              }
              product{
                color
                size
                productMaster{
            productMasterId
                name 
                  name
                  thumbnail
                  brand{
                    name
                  }
                  category{
                    name
                  }
                  subCategory{
                    name
                  }
                }
              }
              quantity
              priceTotal
            }
          }
        }
      }
    }
  """;

  static const String myOrderByPk = """
    query orderMaster(\$id: Int!){
      defaultBankAccount{
        bankName
        accountNo
        ownerName
      }
      orderMaster(orderMasterId: \$id){
        dateCreated
        id
        orderNumber
        coupon{
          couponName
          price
        }
        priceToPay
        paymentSuccess{
          amount
          requestedAt
          method
        }
        paymentRequest{
          method
          requestedAt
          amount
        }
        priceDelivery
        receiver
        address
        detailAddress
        smarterMoneyHistory{
          amount
        }
        zipCode
        phone
        deliveryRequest
        details {
        orderDetailId
          userRequest
          studentNames
          draft{
            image
            priceWork
            font
            threadColor
          }
          state
          product{
            color
            size
            productMaster{
            productMasterId
              name
              thumbnail
              brand{
                name
              }
              category{
                name
              }
              subCategory{
                name
              }
            }
            name 
          }
          quantity
          priceTotal
          priceProducts
          priceWork
          priceWorkLabor
          priceOption
          }
      }
    }
  """;

  static const String orderMasterAndAddresses = """
    query OrderMaster( \$orderMasterId: Int!){
      myAddresses {
        id
        name
        receiver
        phone
        zipCode
        address
        detailAddress
        default
      }
      myCoupons{
        id
        couponMaster{
          name
        }
        price
        startOfUse
        endOfUse
      }
      orderMaster(orderMasterId: \$orderMasterId){
        id
        orderNumber
        priceDelivery
        priceTotalProducts
        priceToPay
        orderName
        receiver
        address
        detailAddress
        zipCode
        phone
        details{
          state
          product{
            color
            size
            productMaster{
              name
              thumbnail
              brand{
                name
              }
              category{
                name
              }
              subCategory{
                name
              }
            }
            name 
          }
          quantity
          priceTotal
          priceProducts
          priceWork
          priceWorkLabor
          priceOption
        }
      }
    }
  """;
}
